### ISSUE TITLE
How to get the source code?

### ISSUE THREAD

**Issue by yangxuan8282** [raspberrypi-ui/chromium_patches#1]
Would you mind if I ask where can I get the source code? The latest patches is for 60.0.3112.89, but seems the source code not provided on http://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/ . For some other version like 60.0.3112.90 I can found it on https://commondatastorage.googleapis.com/chromium-browser-official/chromium-60.0.3112.90.tar.xz , but can't found the 60.0.3112.89 one. Use the chromium official tools git clone whole repository, and checkout to 60.0.3112.89, then I found missing some files and folder like `native_client/src/include/concurrency_ops.h`.

**Comment by spl237** [comment]
The patch contains all the files we modify for a standard Chromium build - your question is therefore a standard Chromium build query and not anything Pi-specific; I suggest you ask on the Chromium repo or forums.
